name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - { 
            os: ubuntu-latest,
            os_label: ubuntu,
            tag: py36,
            python_version: 3.6
          }
        - {
            os: ubuntu-latest,
            os_label: ubuntu,
            tag: py37,
            python_version: 3.7
          }
        - {
            os: ubuntu-latest,
            os_label: ubuntu,
            tag: py38,
            python_version: 3.8
          }
        - {
            os: ubuntu-latest,
            os_label: ubuntu,
            tag: py39,
            python_version: 3.9
          }
        - {
            os: windows-latest,
            os_label: windows,
            tag: py36,
            python_version: 3.6.8
          }
        - {
            os: windows-latest,
            os_label: windows,
            tag: py37,
            python_version: 3.7.9
          }
        - {
            os: windows-latest,
            os_label: windows,
            tag: py38,
            python_version: 3.8.9
          }
        - {
            os: windows-latest,
            os_label: windows,
            tag: py39,
            python_version: 3.9.6
          }
    runs-on: ${{ matrix.config.os }} 
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cp requirements.txt ${{ matrix.config.os_label }}/requirements.txt
        docker build --build-arg python_version=${{ matrix.config.python_version}} --tag joergbrech/cpp_python_vtk_qt-${{ matrix.config.os_label }}:${{ matrix.config.tag }} ${{ matrix.config.os_label }}
        
